/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    // Keep a lightweight footprint; avoid compile-only deps on LWJGL.
    // We use reflection for LWJGL so no additional deps here.
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
    withSourcesJar()
}

tasks.jar {
    manifest {
        attributes(
            mapOf(
                // Java Agent entrypoints
                "Premain-Class" to "work.stdpi.finger.agent.FingerAgent",
                "Agent-Class" to "work.stdpi.finger.agent.FingerAgent",
                "Can-Redefine-Classes" to "true",
                "Can-Retransform-Classes" to "true"
            )
        )
    }
}
